Update to otp-react-redux 2
ibi-group/trimet-mod-otp pull request #285
Opened 2021-01-08 23:51 UTC by evansiroky

Depends on #284.

Updates the code to work with otp-react-redux 2.0.

2021-01-11 16:12 UTC, landonreed requested changes
Runs, looks great. A couple of minor things though:
- The PR title and description should be updated to include "GitHub actions" change (for future searchability).
- When I run locally I see the following error being thrown. Do you know if this is due to changes in otp-rr v2?
![image](https://user-images.githubusercontent.com/2370911/104206729-e17f9c00-53fd-11eb-9a2d-9a5bb94044ae.png)

2021-01-11 20:28 UTC, binh-dam-ibigroup approved these changes

2021-01-13 21:40 UTC, evansiroky commented
This PR is just for 2.0 and the commits reflect that now that I merged master into this branch.

The nasty error you screenshotted exists in master and I've spent several hours trying to track it down without much success. It does not appear to stop the website from loading.

2021-01-14 14:53 UTC, landonreed approved these changes

2021-01-14 14:53 UTC, merged